import type { Metadata } from "next";
import "./globals.css";

import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
    title: "Food Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex bg-slate-100">
                <SideBar />
                <main>{children}</main>
            </body>
        </html>
    );
}
